package net.ymate.module.fileuploader.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * AttachmentMeta generated By EntityGenerator on 2016/11/03 上午 04:21:08
 *
 * @author YMP
 * @version 1.0
 */
@Entity("attachment_meta")
public class AttachmentMeta extends BaseEntity<AttachmentMeta, java.lang.String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private java.lang.String id;

    @Property(name = "usage_size", length = 20)
    @Default("0")
    @PropertyState(propertyName = "usage_size")
    private java.lang.Long usageSize;

    @Property(name = "max_size", length = 20)
    @Default("0")
    @PropertyState(propertyName = "max_size")
    private java.lang.Long maxSize;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private java.lang.String siteId;

    @Property(name = "create_time", nullable = false, length = 13)
    @PropertyState(propertyName = "create_time")
    @Readonly
    private java.lang.Long createTime;

    @Property(name = "last_modify_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "last_modify_time")
    private java.lang.Long lastModifyTime;

    /**
     * 构造器
     */
    public AttachmentMeta() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param siteId
     * @param createTime
     */
    public AttachmentMeta(java.lang.String id, java.lang.String siteId, java.lang.Long createTime) {
        this.id = id;
        this.siteId = siteId;
        this.createTime = createTime;
    }

    /**
     * 构造器
     *
     * @param id
     * @param usageSize
     * @param maxSize
     * @param siteId
     * @param createTime
     * @param lastModifyTime
     */
    public AttachmentMeta(java.lang.String id, java.lang.Long usageSize, java.lang.Long maxSize, java.lang.String siteId, java.lang.Long createTime, java.lang.Long lastModifyTime) {
        this.id = id;
        this.usageSize = usageSize;
        this.maxSize = maxSize;
        this.siteId = siteId;
        this.createTime = createTime;
        this.lastModifyTime = lastModifyTime;
    }

    public java.lang.String getId() {
        return id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }


    /**
     * @return the usageSize
     */
    public java.lang.Long getUsageSize() {
        return usageSize;
    }

    /**
     * @param usageSize the usageSize to set
     */
    public void setUsageSize(java.lang.Long usageSize) {
        this.usageSize = usageSize;
    }

    /**
     * @return the maxSize
     */
    public java.lang.Long getMaxSize() {
        return maxSize;
    }

    /**
     * @param maxSize the maxSize to set
     */
    public void setMaxSize(java.lang.Long maxSize) {
        this.maxSize = maxSize;
    }

    /**
     * @return the siteId
     */
    public java.lang.String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(java.lang.String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the createTime
     */
    public java.lang.Long getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(java.lang.Long createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the lastModifyTime
     */
    public java.lang.Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(java.lang.Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static AttachmentMetaBuilder builder() {
        return new AttachmentMetaBuilder();
    }

    public AttachmentMetaBuilder bind() {
        return new AttachmentMetaBuilder(this);
    }

    public static class AttachmentMetaBuilder {

        private AttachmentMeta _model;

        public AttachmentMetaBuilder() {
            _model = new AttachmentMeta();
        }

        public AttachmentMetaBuilder(AttachmentMeta model) {
            _model = model;
        }

        public AttachmentMeta build() {
            return _model;
        }

        public java.lang.String id() {
            return _model.getId();
        }

        public AttachmentMetaBuilder id(java.lang.String id) {
            _model.setId(id);
            return this;
        }

        public java.lang.Long usageSize() {
            return _model.getUsageSize();
        }

        public AttachmentMetaBuilder usageSize(java.lang.Long usageSize) {
            _model.setUsageSize(usageSize);
            return this;
        }

        public java.lang.Long maxSize() {
            return _model.getMaxSize();
        }

        public AttachmentMetaBuilder maxSize(java.lang.Long maxSize) {
            _model.setMaxSize(maxSize);
            return this;
        }

        public java.lang.String siteId() {
            return _model.getSiteId();
        }

        public AttachmentMetaBuilder siteId(java.lang.String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public java.lang.Long createTime() {
            return _model.getCreateTime();
        }

        public AttachmentMetaBuilder createTime(java.lang.Long createTime) {
            _model.setCreateTime(createTime);
            return this;
        }

        public java.lang.Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public AttachmentMetaBuilder lastModifyTime(java.lang.Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * AttachmentMeta 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String USAGE_SIZE = "usage_size";
        public static final String MAX_SIZE = "max_size";
        public static final String SITE_ID = "site_id";
        public static final String CREATE_TIME = "create_time";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "attachment_meta";

}
