package net.ymate.module.fileuploader.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * AttachmentAttribute generated By EntityGenerator on 2016/11/03 上午 04:21:08
 *
 * @author YMP
 * @version 1.0
 */
@Entity(AttachmentAttribute.TABLE_NAME)
public class AttachmentAttribute extends BaseEntity<AttachmentAttribute, java.lang.String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = FIELDS.ID, nullable = false, length = 32)
    @PropertyState(propertyName = FIELDS.ID)
    private java.lang.String id;

    @Property(name = FIELDS.ATTACHMENT_ID, nullable = false, length = 32)
    @PropertyState(propertyName = FIELDS.ATTACHMENT_ID)
    private java.lang.String attachmentId;

    @Property(name = FIELDS.ATTR_KEY, nullable = false, length = 100)
    @PropertyState(propertyName = FIELDS.ATTR_KEY)
    private java.lang.String attrKey;

    @Property(name = FIELDS.ATTR_VALUE, length = 16383)
    @PropertyState(propertyName = FIELDS.ATTR_VALUE)
    private java.lang.String attrValue;

    @Property(name = FIELDS.TYPE, unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = FIELDS.TYPE)
    private java.lang.Integer type;

    @Property(name = FIELDS.OWNER, length = 32)
    @PropertyState(propertyName = FIELDS.OWNER)
    private java.lang.String owner;

    @Property(name = FIELDS.CREATE_TIME, nullable = false, length = 13)
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
    @Readonly
    private java.lang.Long createTime;

    @Property(name = FIELDS.LAST_MODIFY_TIME, length = 13)
    @Default("0")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_TIME)
    private java.lang.Long lastModifyTime;

    /**
     * 构造器
     */
    public AttachmentAttribute() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param attachmentId
     * @param attrKey
     * @param createTime
     */
    public AttachmentAttribute(java.lang.String id, java.lang.String attachmentId, java.lang.String attrKey, java.lang.Long createTime) {
        this.id = id;
        this.attachmentId = attachmentId;
        this.attrKey = attrKey;
        this.createTime = createTime;
    }

    /**
     * 构造器
     *
     * @param id
     * @param attachmentId
     * @param attrKey
     * @param attrValue
     * @param type
     * @param owner
     * @param createTime
     * @param lastModifyTime
     */
    public AttachmentAttribute(java.lang.String id, java.lang.String attachmentId, java.lang.String attrKey, java.lang.String attrValue, java.lang.Integer type, java.lang.String owner, java.lang.Long createTime, java.lang.Long lastModifyTime) {
        this.id = id;
        this.attachmentId = attachmentId;
        this.attrKey = attrKey;
        this.attrValue = attrValue;
        this.type = type;
        this.owner = owner;
        this.createTime = createTime;
        this.lastModifyTime = lastModifyTime;
    }

    @Override
    public java.lang.String getId() {
        return id;
    }

    @Override
    public void setId(java.lang.String id) {
        this.id = id;
    }


    /**
     * @return the attachmentId
     */
    public java.lang.String getAttachmentId() {
        return attachmentId;
    }

    /**
     * @param attachmentId the attachmentId to set
     */
    public void setAttachmentId(java.lang.String attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * @return the attrKey
     */
    public java.lang.String getAttrKey() {
        return attrKey;
    }

    /**
     * @param attrKey the attrKey to set
     */
    public void setAttrKey(java.lang.String attrKey) {
        this.attrKey = attrKey;
    }

    /**
     * @return the attrValue
     */
    public java.lang.String getAttrValue() {
        return attrValue;
    }

    /**
     * @param attrValue the attrValue to set
     */
    public void setAttrValue(java.lang.String attrValue) {
        this.attrValue = attrValue;
    }

    /**
     * @return the type
     */
    public java.lang.Integer getType() {
        return type;
    }

    /**
     * @param type the type to set
     */
    public void setType(java.lang.Integer type) {
        this.type = type;
    }

    /**
     * @return the owner
     */
    public java.lang.String getOwner() {
        return owner;
    }

    /**
     * @param owner the owner to set
     */
    public void setOwner(java.lang.String owner) {
        this.owner = owner;
    }

    /**
     * @return the createTime
     */
    public java.lang.Long getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(java.lang.Long createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the lastModifyTime
     */
    public java.lang.Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(java.lang.Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static AttachmentAttributeBuilder builder() {
        return new AttachmentAttributeBuilder();
    }

    public AttachmentAttributeBuilder bind() {
        return new AttachmentAttributeBuilder(this);
    }

    public static class AttachmentAttributeBuilder {

        private AttachmentAttribute _model;

        public AttachmentAttributeBuilder() {
            _model = new AttachmentAttribute();
        }

        public AttachmentAttributeBuilder(AttachmentAttribute model) {
            _model = model;
        }

        public AttachmentAttribute build() {
            return _model;
        }


        public IConnectionHolder connectionHolder() {
            return _model.getConnectionHolder();
        }

        public AttachmentAttributeBuilder connectionHolder(IConnectionHolder connectionHolder) {
            _model.setConnectionHolder(connectionHolder);
            return this;
        }

        public String dataSourceName() {
            return _model.getDataSourceName();
        }

        public AttachmentAttributeBuilder dataSourceName(String dsName) {
            _model.setDataSourceName(dsName);
            return this;
        }

        public IShardingable shardingable() {
            return _model.getShardingable();
        }

        public AttachmentAttributeBuilder shardingable(IShardingable shardingable) {
            _model.setShardingable(shardingable);
            return this;
        }

        public java.lang.String id() {
            return _model.getId();
        }

        public AttachmentAttributeBuilder id(java.lang.String id) {
            _model.setId(id);
            return this;
        }

        public java.lang.String attachmentId() {
            return _model.getAttachmentId();
        }

        public AttachmentAttributeBuilder attachmentId(java.lang.String attachmentId) {
            _model.setAttachmentId(attachmentId);
            return this;
        }

        public java.lang.String attrKey() {
            return _model.getAttrKey();
        }

        public AttachmentAttributeBuilder attrKey(java.lang.String attrKey) {
            _model.setAttrKey(attrKey);
            return this;
        }

        public java.lang.String attrValue() {
            return _model.getAttrValue();
        }

        public AttachmentAttributeBuilder attrValue(java.lang.String attrValue) {
            _model.setAttrValue(attrValue);
            return this;
        }

        public java.lang.Integer type() {
            return _model.getType();
        }

        public AttachmentAttributeBuilder type(java.lang.Integer type) {
            _model.setType(type);
            return this;
        }

        public java.lang.String owner() {
            return _model.getOwner();
        }

        public AttachmentAttributeBuilder owner(java.lang.String owner) {
            _model.setOwner(owner);
            return this;
        }

        public java.lang.Long createTime() {
            return _model.getCreateTime();
        }

        public AttachmentAttributeBuilder createTime(java.lang.Long createTime) {
            _model.setCreateTime(createTime);
            return this;
        }

        public java.lang.Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public AttachmentAttributeBuilder lastModifyTime(java.lang.Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * AttachmentAttribute 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String ATTACHMENT_ID = "attachment_id";
        public static final String ATTR_KEY = "attr_key";
        public static final String ATTR_VALUE = "attr_value";
        public static final String TYPE = "type";
        public static final String OWNER = "owner";
        public static final String CREATE_TIME = "create_time";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "attachment_attribute";

}
